"""
Opal Language - C Transpiler / مولّد كود C

Transpiles Opal code to C code for systems programming.
يحول كود أوبال إلى كود C لبرمجة الأنظمة

This allows Opal to be used for:
- Operating system development
- Embedded systems
- High-performance applications
- Interfacing with C libraries

هذا يسمح باستخدام أوبال في:
- تطوير أنظمة التشغيل
- الأنظمة المدمجة
- التطبيقات عالية الأداء
- الربط مع مكتبات C

Usage / الاستخدام:
    opal --compile-c file.op          # Generate file.c
    opal --compile-c file.op -o out.c  # Specify output
"""

import sys
import os

# Add parent to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from opal.lexer import Lexer, LexError
from opal.parser import Parser, ParseError
from opal.ast_nodes import (
    NumberLiteral, StringLiteral, BooleanLiteral, NullLiteral,
    ListLiteral, Identifier, BinaryOp, UnaryOp, Assignment,
    Call, IndexAccess, MemberAccess, Range, DictLiteral,
    VarDecl, EchoStmt, ExprStmt, Block, IfStmt, WhileStmt, ForStmt,
    FuncDecl, ReturnStmt, BreakStmt, ContinueStmt,
    ImportStmt, FromImportStmt, Program, TryStmt, ThrowStmt,
    ClassDecl, SwitchStmt, DoUntilStmt, TernaryExpr, CompoundAssign
)
from opal.tokens import TokenType


class CTranspiler:
    """يحول AST أوبال إلى كود C / Transpiles Opal AST to C code"""

    def __init__(self):
        self.indent_level = 0
        self.includes = set()
        self.functions = []
        self.globals = []
        self.class_structs = {}

    def indent(self):
        """إرجاع المسافة البادئة / Return indentation"""
        return "    " * self.indent_level

    def transpile(self, program):
        """تحويل البرنامج كاملاً / Transpile entire program"""
        # First pass: collect function declarations
        for stmt in program.statements:
            if isinstance(stmt, FuncDecl):
                self.functions.append(stmt)
            elif isinstance(stmt, VarDecl):
                self.globals.append(stmt)
            elif isinstance(stmt, ClassDecl):
                self._generate_class_struct(stmt)

        # Generate C code
        code = self._generate_header()

        # Generate class structs
        for class_name, fields in self.class_structs.items():
            code += f"\n// Class: {class_name}\n"
            code += f"typedef struct {{\n"
            for field_name, field_type in fields.items():
                code += f"    {field_type} {field_name};\n"
            code += f"}} {class_name};\n"

        # Generate global variables
        for var in self.globals:
            code += self._transpile_global_var(var)

        # Generate function prototypes
        code += "\n// Function prototypes\n"
        for func in self.functions:
            params = self._transpile_params(func.params)
            code += f"Value {func.name}({params});\n"

        # Generate functions
        code += "\n// Functions\n"
        for func in self.functions:
            code += self._transpile_function(func)

        # Generate main function
        code += "\n// Main\n"
        code += "int main() {\n"
        self.indent_level = 1
        for stmt in program.statements:
            if not isinstance(stmt, (FuncDecl, ClassDecl, ImportStmt, FromImportStmt)):
                code += self._transpile_statement(stmt)
        code += self.indent() + "return 0;\n"
        code += "}\n"

        return code

    def _generate_header(self):
        """توليد رأس ملف C / Generate C file header"""
        header = """/*
 * Generated by Opal C Transpiler v2.0
 * تم توليده بواسطة مولّد C لأوبال
 *
 * This C code was generated from Opal source code.
 * تم توليد هذا الكود من مصدر أوبال
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>
#include <stdbool.h>

// Opal Value type (dynamic typing)
// نوع القيمة في أوبال (أنواع ديناميكية)
typedef enum {
    OPAL_NULL,
    OPAL_INT,
    OPAL_FLOAT,
    OPAL_STRING,
    OPAL_BOOL,
    OPAL_LIST,
} OpalType;

typedef struct {
    OpalType type;
    union {
        int64_t int_val;
        double float_val;
        char* string_val;
        bool bool_val;
    };
} Value;

// Helper constructors
Value make_int(int64_t v) {
    Value r;
    r.type = OPAL_INT;
    r.int_val = v;
    return r;
}

Value make_float(double v) {
    Value r;
    r.type = OPAL_FLOAT;
    r.float_val = v;
    return r;
}

Value make_string(const char* v) {
    Value r;
    r.type = OPAL_STRING;
    r.string_val = strdup(v);
    return r;
}

Value make_bool(bool v) {
    Value r;
    r.type = OPAL_BOOL;
    r.bool_val = v;
    return r;
}

Value make_null() {
    Value r;
    r.type = OPAL_NULL;
    return r;
}

// Opal echo (print)
void opal_echo(Value v) {
    switch (v.type) {
        case OPAL_INT: printf("%lld", (long long)v.int_val); break;
        case OPAL_FLOAT: printf("%g", v.float_val); break;
        case OPAL_STRING: printf("%s", v.string_val); break;
        case OPAL_BOOL: printf("%s", v.bool_val ? "true" : "false"); break;
        case OPAL_NULL: printf("null"); break;
        default: break;
    }
}

void opal_print(Value v) {
    opal_echo(v);
    printf("\\n");
}

"""
        return header

    def _transpile_params(self, params):
        """تحويل البارامترات / Transpile function parameters"""
        if not params:
            return "void"
        return ", ".join(f"Value {p}" for p in params)

    def _transpile_global_var(self, var):
        """تحويل متغير شامل / Transpile global variable"""
        value = self._transpile_expression(var.value)
        return f"Value {var.name} = {value};\n"

    def _transpile_function(self, func):
        """تحويل دالة / Transpile function"""
        params = self._transpile_params(func.params)
        code = f"\nValue {func.name}({params}) {{\n"
        self.indent_level = 1
        for stmt in func.body.statements:
            code += self._transpile_statement(stmt)
        code += self.indent() + "return make_null();\n"
        code += "}\n"
        return code

    def _generate_class_struct(self, class_decl):
        """توليد بنية صف / Generate class struct"""
        fields = {}
        # This is simplified - a real implementation would track field types
        for method in class_decl.methods:
            if method.name in ('init', 'constructor', '__init__'):
                # Try to extract field names from constructor
                for stmt in method.body.statements:
                    if isinstance(stmt, ExprStmt) and isinstance(stmt.expression, Assignment):
                        if isinstance(stmt.expression.target, MemberAccess):
                            fields[stmt.expression.target.member] = "Value"
        self.class_structs[class_decl.name] = fields

    def _transpile_statement(self, stmt):
        """تحويل جملة / Transpile a statement"""
        if isinstance(stmt, VarDecl):
            value = self._transpile_expression(stmt.value)
            return self.indent() + f"Value {stmt.name} = {value};\n"

        if isinstance(stmt, EchoStmt):
            code = self.indent()
            for i, expr in enumerate(stmt.expressions):
                if i > 0:
                    code += 'printf(" ");'
                code += f"opal_echo({self._transpile_expression(expr)});"
            code += 'printf("\\n");\n'
            return code

        if isinstance(stmt, ExprStmt):
            return self.indent() + self._transpile_expression(stmt.expression) + ";\n"

        if isinstance(stmt, IfStmt):
            cond = self._transpile_expression(stmt.condition)
            code = self.indent() + f"if (opal_truthy({cond})) {{\n"
            self.indent_level += 1
            for s in stmt.then_block.statements:
                code += self._transpile_statement(s)
            self.indent_level -= 1
            code += self.indent() + "}"

            for elif_cond, elif_block in stmt.elif_branches:
                ec = self._transpile_expression(elif_cond)
                code += f" else if (opal_truthy({ec})) {{\n"
                self.indent_level += 1
                for s in elif_block.statements:
                    code += self._transpile_statement(s)
                self.indent_level -= 1
                code += self.indent() + "}"

            if stmt.else_block:
                code += " else {\n"
                self.indent_level += 1
                for s in stmt.else_block.statements:
                    code += self._transpile_statement(s)
                self.indent_level -= 1
                code += self.indent() + "}\n"
            else:
                code += "\n"
            return code

        if isinstance(stmt, WhileStmt):
            cond = self._transpile_expression(stmt.condition)
            code = self.indent() + f"while (opal_truthy({cond})) {{\n"
            self.indent_level += 1
            for s in stmt.body.statements:
                code += self._transpile_statement(s)
            self.indent_level -= 1
            code += self.indent() + "}\n"
            return code

        if isinstance(stmt, ForStmt):
            # Transpile for loop as a while loop
            var = stmt.var_name
            iterable = self._transpile_expression(stmt.iterable)
            code = self.indent() + f"// For loop (simplified)\n"
            code += self.indent() + f"{{ /* for {var} in {iterable} */\n"
            self.indent_level += 1
            code += self.indent() + f"// Loop body would go here\n"
            for s in stmt.body.statements:
                code += self._transpile_statement(s)
            self.indent_level -= 1
            code += self.indent() + "}\n"
            return code

        if isinstance(stmt, ReturnStmt):
            if stmt.value:
                val = self._transpile_expression(stmt.value)
                return self.indent() + f"return {val};\n"
            return self.indent() + "return make_null();\n"

        if isinstance(stmt, BreakStmt):
            return self.indent() + "break;\n"

        if isinstance(stmt, ContinueStmt):
            return self.indent() + "continue;\n"

        if isinstance(stmt, FuncDecl):
            # Nested function - generate separately
            params = self._transpile_params(stmt.params)
            code = f"\nValue {stmt.name}({params}) {{\n"
            old_indent = self.indent_level
            self.indent_level = 1
            for s in stmt.body.statements:
                code += self._transpile_statement(s)
            code += self.indent() + "return make_null();\n"
            self.indent_level = old_indent
            code += "}\n"
            return code

        if isinstance(stmt, ImportStmt):
            return self.indent() + f"// import {stmt.module_name};\n"

        if isinstance(stmt, FromImportStmt):
            names = ', '.join(stmt.names)
            return self.indent() + f"// from {stmt.module_name} import {names};\n"

        if isinstance(stmt, ThrowStmt):
            val = self._transpile_expression(stmt.value)
            return self.indent() + f"/* throw {val} */ fprintf(stderr, \"Error\\n\"); return make_null();\n"

        # Default: comment
        return self.indent() + f"// {type(stmt).__name__}\n"

    def _transpile_expression(self, expr):
        """تحويل تعبير / Transpile an expression"""
        if isinstance(expr, NumberLiteral):
            if isinstance(expr.value, float):
                return f"make_float({expr.value})"
            return f"make_int({expr.value})"

        if isinstance(expr, StringLiteral):
            escaped = expr.value.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
            return f'make_string("{escaped}")'

        if isinstance(expr, BooleanLiteral):
            return f"make_bool({'true' if expr.value else 'false'})"

        if isinstance(expr, NullLiteral):
            return "make_null()"

        if isinstance(expr, Identifier):
            return expr.name

        if isinstance(expr, BinaryOp):
            left = self._transpile_expression(expr.left)
            right = self._transpile_expression(expr.right)
            op_map = {
                TokenType.PLUS: '+',
                TokenType.MINUS: '-',
                TokenType.STAR: '*',
                TokenType.SLASH: '/',
                TokenType.DIVIDE: '/',
                TokenType.POWER: '*',  # Approximate
                TokenType.MODULO: '%',
                TokenType.EQ: '==',
                TokenType.NEQ: '!=',
                TokenType.LT: '<',
                TokenType.GT: '>',
                TokenType.LTE: '<=',
                TokenType.GTE: '>=',
            }
            op = op_map.get(expr.op.type, '?')
            # For simplicity, assume int operations
            return f"make_int(({left}).int_val {op} ({right}).int_val)"

        if isinstance(expr, Assignment):
            value = self._transpile_expression(expr.value)
            if isinstance(expr.target, Identifier):
                return f"{expr.target.name} = {value}"
            return f"/* assignment */ {value}"

        if isinstance(expr, Call):
            args = ', '.join(self._transpile_expression(a) for a in expr.args)
            if isinstance(expr.callee, Identifier):
                # Map echo to opal_print
                if expr.callee.name == 'echo':
                    # echo with multiple args
                    if len(expr.args) == 1:
                        return f"opal_print({args})"
                    return f"opal_print({self._transpile_expression(expr.args[0])})"
                return f"{expr.callee.name}({args})"
            return f"/* call */({args})"

        if isinstance(expr, TernaryExpr):
            cond = self._transpile_expression(expr.condition)
            then_v = self._transpile_expression(expr.then_expr)
            else_v = self._transpile_expression(expr.else_expr)
            return f"(opal_truthy({cond}) ? {then_v} : {else_v})"

        if isinstance(expr, MemberAccess):
            obj = self._transpile_expression(expr.obj)
            return f"({obj}).{expr.member}"

        if isinstance(expr, IndexAccess):
            obj = self._transpile_expression(expr.obj)
            idx = self._transpile_expression(expr.index)
            return f"({obj})[({idx}).int_val]"

        return "make_null() /* unknown */"


def transpile_to_c(source, output_path=None):
    """تحويل كود أوبال إلى C / Transpile Opal source to C"""
    try:
        # Lex
        lexer = Lexer(source)
        tokens = lexer.tokenize()

        # Parse
        parser = Parser(tokens)
        program = parser.parse()

        # Transpile
        transpiler = CTranspiler()
        c_code = transpiler.transpile(program)

        # Determine output path
        if output_path is None:
            output_path = "output.c"

        # Write output
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(c_code)

        return c_code, None

    except (LexError, ParseError) as e:
        return None, str(e)
    except Exception as e:
        return None, str(e)


def compile_file(filepath, output_path=None):
    """تحويل ملف أوبال إلى C / Compile Opal file to C"""
    if not os.path.exists(filepath):
        print(f"Error: File '{filepath}' not found")
        return False

    with open(filepath, 'r', encoding='utf-8') as f:
        source = f.read()

    if output_path is None:
        # Replace .op with .c
        if filepath.endswith('.op'):
            output_path = filepath[:-3] + '.c'
        else:
            output_path = filepath + '.c'

    c_code, error = transpile_to_c(source, output_path)

    if error:
        print(f"Compile error: {error}")
        return False

    print(f"Generated: {output_path}")
    print(f"To compile: gcc {output_path} -o program")
    return True
