"""
Opal Language - C Transpiler v2 / مولّد كود C محسّن

Transpiles Opal code to C code for systems programming.
يحول كود أوبال إلى كود C لبرمجة الأنظمة

Supports:
- Variables and constants
- Functions (with recursion)
- Control flow: if/elif/else, while, for, break, continue
- Arithmetic, comparison, logical operators
- String concatenation
- Lists (simplified)
- Echo/print

Usage / الاستخدام:
    opal file.op --compile-c -o output.c
    gcc output.c -o program
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from opal.lexer import Lexer, LexError
from opal.parser import Parser, ParseError
from opal.ast_nodes import (
    NumberLiteral, StringLiteral, BooleanLiteral, NullLiteral,
    ListLiteral, Identifier, BinaryOp, UnaryOp, Assignment,
    Call, IndexAccess, MemberAccess, Range,
    VarDecl, EchoStmt, ExprStmt, Block, IfStmt, WhileStmt, ForStmt,
    FuncDecl, ReturnStmt, BreakStmt, ContinueStmt,
    ImportStmt, FromImportStmt, Program, TernaryExpr, CompoundAssign
)
from opal.tokens import TokenType


C_RUNTIME_HEADER = """/*
 * Generated by Opal C Transpiler v2.1
 * تم توليده بواسطة مولّد C لأوبال
 *
 * Compile with / ترجمة بـ:
 *   gcc -o program output.c -lm
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>
#include <stdbool.h>

/* === Opal Runtime === */

typedef enum {
    OPAL_NULL,
    OPAL_INT,
    OPAL_FLOAT,
    OPAL_STRING,
    OPAL_BOOL,
} OpalType;

typedef struct {
    OpalType type;
    union {
        int64_t int_val;
        double float_val;
        char* string_val;
        bool bool_val;
    };
} Value;

static Value make_int(int64_t v) {
    Value r; r.type = OPAL_INT; r.int_val = v; return r;
}

static Value make_float(double v) {
    Value r; r.type = OPAL_FLOAT; r.float_val = v; return r;
}

static Value make_string(const char* v) {
    Value r; r.type = OPAL_STRING;
    r.string_val = (char*)malloc(strlen(v) + 1);
    strcpy(r.string_val, v);
    return r;
}

static Value make_bool(bool v) {
    Value r; r.type = OPAL_BOOL; r.bool_val = v; return r;
}

static Value make_null(void) {
    Value r; r.type = OPAL_NULL; return r;
}

static bool opal_truthy(Value v) {
    switch (v.type) {
        case OPAL_INT: return v.int_val != 0;
        case OPAL_FLOAT: return v.float_val != 0.0;
        case OPAL_STRING: return v.string_val != NULL && v.string_val[0] != '\\0';
        case OPAL_BOOL: return v.bool_val;
        case OPAL_NULL: return false;
        default: return false;
    }
}

static Value opal_add(Value a, Value b) {
    /* String concatenation */
    if (a.type == OPAL_STRING || b.type == OPAL_STRING) {
        char buf_a[256];
        char buf_b[256];
        const char* sa;
        const char* sb;
        if (a.type == OPAL_STRING) sa = a.string_val;
        else { snprintf(buf_a, sizeof(buf_a), "%lld", (long long)a.int_val); sa = buf_a; }
        if (b.type == OPAL_STRING) sb = b.string_val;
        else { snprintf(buf_b, sizeof(buf_b), "%lld", (long long)b.int_val); sb = buf_b; }
        size_t len = strlen(sa) + strlen(sb) + 1;
        char* result = (char*)malloc(len);
        strcpy(result, sa);
        strcat(result, sb);
        Value r; r.type = OPAL_STRING; r.string_val = result;
        return r;
    }
    /* Numeric addition */
    if (a.type == OPAL_FLOAT || b.type == OPAL_FLOAT) {
        double da = (a.type == OPAL_FLOAT) ? a.float_val : (double)a.int_val;
        double db = (b.type == OPAL_FLOAT) ? b.float_val : (double)b.int_val;
        return make_float(da + db);
    }
    return make_int(a.int_val + b.int_val);
}

static Value opal_sub(Value a, Value b) {
    if (a.type == OPAL_FLOAT || b.type == OPAL_FLOAT) {
        double da = (a.type == OPAL_FLOAT) ? a.float_val : (double)a.int_val;
        double db = (b.type == OPAL_FLOAT) ? b.float_val : (double)b.int_val;
        return make_float(da - db);
    }
    return make_int(a.int_val - b.int_val);
}

static Value opal_mul(Value a, Value b) {
    if (a.type == OPAL_FLOAT || b.type == OPAL_FLOAT) {
        double da = (a.type == OPAL_FLOAT) ? a.float_val : (double)a.int_val;
        double db = (b.type == OPAL_FLOAT) ? b.float_val : (double)b.int_val;
        return make_float(da * db);
    }
    return make_int(a.int_val * b.int_val);
}

static Value opal_div(Value a, Value b) {
    if (a.type == OPAL_FLOAT || b.type == OPAL_FLOAT) {
        double da = (a.type == OPAL_FLOAT) ? a.float_val : (double)a.int_val;
        double db = (b.type == OPAL_FLOAT) ? b.float_val : (double)b.int_val;
        return make_float(da / db);
    }
    return make_int(a.int_val / b.int_val);
}

static Value opal_mod(Value a, Value b) {
    return make_int(a.int_val % b.int_val);
}

static Value opal_eq(Value a, Value b) {
    if (a.type != b.type) return make_bool(false);
    switch (a.type) {
        case OPAL_INT: return make_bool(a.int_val == b.int_val);
        case OPAL_FLOAT: return make_bool(a.float_val == b.float_val);
        case OPAL_STRING: return make_bool(strcmp(a.string_val, b.string_val) == 0);
        case OPAL_BOOL: return make_bool(a.bool_val == b.bool_val);
        case OPAL_NULL: return make_bool(true);
        default: return make_bool(false);
    }
}

static Value opal_lt(Value a, Value b) {
    if (a.type == OPAL_FLOAT || b.type == OPAL_FLOAT) {
        double da = (a.type == OPAL_FLOAT) ? a.float_val : (double)a.int_val;
        double db = (b.type == OPAL_FLOAT) ? b.float_val : (double)b.int_val;
        return make_bool(da < db);
    }
    return make_bool(a.int_val < b.int_val);
}

static void opal_print_value(Value v) {
    switch (v.type) {
        case OPAL_INT: printf("%lld", (long long)v.int_val); break;
        case OPAL_FLOAT: printf("%g", v.float_val); break;
        case OPAL_STRING: printf("%s", v.string_val); break;
        case OPAL_BOOL: printf("%s", v.bool_val ? "true" : "false"); break;
        case OPAL_NULL: printf("null"); break;
        default: break;
    }
}

static void opal_echo(Value v) {
    opal_print_value(v);
}

static void opal_println(Value v) {
    opal_print_value(v);
    printf("\\n");
}

/* Forward declarations for user functions are generated below */

"""


class CTranspiler:
    """يحول AST أوبال إلى كود C / Transpiles Opal AST to C code"""

    def __init__(self):
        self.indent_level = 0
        self.functions = {}  # name -> FuncDecl
        self.globals = []
        self.needs_main = True
        self.temp_counter = 0

    def indent(self):
        return "    " * self.indent_level

    def temp(self, prefix="t"):
        self.temp_counter += 1
        return f"{prefix}{self.temp_counter}"

    def transpile(self, program):
        """تحويل البرنامج كاملاً / Transpile entire program"""
        # First pass: collect function declarations and globals
        # المرة الأولى: جمع تعريفات الدوال والمتغيرات الشاملة
        for stmt in program.statements:
            if isinstance(stmt, FuncDecl):
                self.functions[stmt.name] = stmt
            elif isinstance(stmt, VarDecl):
                self.globals.append(stmt)

        # Generate C code
        code = C_RUNTIME_HEADER

        # Function prototypes
        code += "\n/* Function prototypes */\n"
        for fname, func in self.functions.items():
            params = self._transpile_params(func.params)
            code += f"static Value {fname}({params});\n"

        # Declare globals as extern (defined in main)
        # إعلان المتغيرات الشاملة كـ extern (تُعرّف في main)
        if self.globals:
            code += "\n/* Global variables (declared extern, defined in main) */\n"
            for var in self.globals:
                code += f"static Value {var.name};\n"

        # Function definitions
        code += "\n/* Function definitions */\n"
        for fname, func in self.functions.items():
            code += self._transpile_function(func)

        # Main function
        code += "\n/* Main entry point */\n"
        code += "int main(void) {\n"
        self.indent_level = 1

        # Initialize globals first / تهيئة المتغيرات الشاملة أولاً
        if self.globals:
            code += self.indent() + "/* Initialize globals */\n"
            for var in self.globals:
                value = self._transpile_expression(var.value)
                code += self.indent() + f"{var.name} = {value};\n"

        # Execute main statements / تنفيذ الجمل الرئيسية
        for stmt in program.statements:
            if not isinstance(stmt, (FuncDecl, ImportStmt, FromImportStmt, VarDecl)):
                code += self._transpile_statement(stmt)
        code += self.indent() + "return 0;\n"
        code += "}\n"

        return code

    def _transpile_params(self, params):
        if not params:
            return "void"
        return ", ".join(f"Value {p}" for p in params)

    def _transpile_function(self, func):
        params = self._transpile_params(func.params)
        code = f"\nstatic Value {func.name}({params}) {{\n"
        self.indent_level = 1
        for stmt in func.body.statements:
            code += self._transpile_statement(stmt)
        code += self.indent() + "return make_null();\n"
        code += "}\n"
        return code

    def _transpile_statement(self, stmt):
        """تحويل جملة / Transpile a statement"""
        if isinstance(stmt, VarDecl):
            value = self._transpile_expression(stmt.value)
            return self.indent() + f"Value {stmt.name} = {value};\n"

        if isinstance(stmt, EchoStmt):
            # echo a, b, c -> print "a b c\n"
            if len(stmt.expressions) == 1:
                expr = self._transpile_expression(stmt.expressions[0])
                return self.indent() + f"opal_println({expr});\n"
            else:
                # Multiple args - use printf with format
                code = self.indent()
                parts = []
                args = []
                for i, expr_node in enumerate(stmt.expressions):
                    if i > 0:
                        parts.append('" "')
                    expr = self._transpile_expression(expr_node)
                    # We need to print each value with proper format
                    # For simplicity, use opal_print_value
                    code += f"opal_print_value({expr});"
                    if i < len(stmt.expressions) - 1:
                        code += 'printf(" ");'
                code += 'printf("\\n");\n'
                return code

        if isinstance(stmt, ExprStmt):
            return self.indent() + self._transpile_expression(stmt.expression) + ";\n"

        if isinstance(stmt, IfStmt):
            cond = self._transpile_expression(stmt.condition)
            code = self.indent() + f"if (opal_truthy({cond})) {{\n"
            self.indent_level += 1
            for s in stmt.then_block.statements:
                code += self._transpile_statement(s)
            self.indent_level -= 1
            code += self.indent() + "}"

            for elif_cond, elif_block in stmt.elif_branches:
                ec = self._transpile_expression(elif_cond)
                code += f" else if (opal_truthy({ec})) {{\n"
                self.indent_level += 1
                for s in elif_block.statements:
                    code += self._transpile_statement(s)
                self.indent_level -= 1
                code += self.indent() + "}"

            if stmt.else_block:
                code += " else {\n"
                self.indent_level += 1
                for s in stmt.else_block.statements:
                    code += self._transpile_statement(s)
                self.indent_level -= 1
                code += self.indent() + "}\n"
            else:
                code += "\n"
            return code

        if isinstance(stmt, WhileStmt):
            cond = self._transpile_expression(stmt.condition)
            code = self.indent() + f"while (opal_truthy({cond})) {{\n"
            self.indent_level += 1
            for s in stmt.body.statements:
                code += self._transpile_statement(s)
            self.indent_level -= 1
            code += self.indent() + "}\n"
            return code

        if isinstance(stmt, ForStmt):
            # for var in iterable { body }
            # If iterable is a Range (a..b), generate a C for loop
            var = stmt.var_name
            if isinstance(stmt.iterable, Range):
                start = self._transpile_expression(stmt.iterable.start)
                end = self._transpile_expression(stmt.iterable.end)
                # Range in Opal is inclusive: 1..5 means 1,2,3,4,5
                # نطاق أوبال شامل: 1..5 يعني 1,2,3,4,5
                code = self.indent() + f"for (Value {var} = {start}; opal_truthy(opal_lt({var}, opal_add({end}, make_int(1)))); {var} = opal_add({var}, make_int(1))) {{\n"
                self.indent_level += 1
                for s in stmt.body.statements:
                    code += self._transpile_statement(s)
                self.indent_level -= 1
                code += self.indent() + "}\n"
                return code
            else:
                # Generic iterable - simplified to comment
                iterable = self._transpile_expression(stmt.iterable)
                code = self.indent() + f"/* TODO: for-each loop over {iterable} */\n"
                code = self.indent() + "{\n"
                self.indent_level += 1
                for s in stmt.body.statements:
                    code += self._transpile_statement(s)
                self.indent_level -= 1
                code += self.indent() + "}\n"
                return code

        if isinstance(stmt, ReturnStmt):
            if stmt.value:
                val = self._transpile_expression(stmt.value)
                return self.indent() + f"return {val};\n"
            return self.indent() + "return make_null();\n"

        if isinstance(stmt, BreakStmt):
            return self.indent() + "break;\n"

        if isinstance(stmt, ContinueStmt):
            return self.indent() + "continue;\n"

        if isinstance(stmt, FuncDecl):
            # Nested function - just call the function transpiler
            return self._transpile_function(stmt)

        if isinstance(stmt, ImportStmt):
            return self.indent() + f"/* import {stmt.module_name}; */\n"

        if isinstance(stmt, FromImportStmt):
            return self.indent() + f"/* from {stmt.module_name} import {', '.join(stmt.names)}; */\n"

        if isinstance(stmt, ThrowStmt):
            val = self._transpile_expression(stmt.value)
            return self.indent() + f"/* throw */ fprintf(stderr, \"Opal error\\n\"); exit(1);\n"

        # Default: comment
        return self.indent() + f"/* unhandled: {type(stmt).__name__} */\n"

    def _transpile_expression(self, expr):
        """تحويل تعبير / Transpile an expression"""
        if isinstance(expr, NumberLiteral):
            if isinstance(expr.value, float):
                return f"make_float({expr.value})"
            return f"make_int({expr.value}LL)"

        if isinstance(expr, StringLiteral):
            escaped = expr.value.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\t', '\\t')
            return f'make_string("{escaped}")'

        if isinstance(expr, BooleanLiteral):
            return f"make_bool({'true' if expr.value else 'false'})"

        if isinstance(expr, NullLiteral):
            return "make_null()"

        if isinstance(expr, Identifier):
            return expr.name

        if isinstance(expr, BinaryOp):
            left = self._transpile_expression(expr.left)
            right = self._transpile_expression(expr.right)

            op = expr.op.type
            if op == TokenType.PLUS:
                return f"opal_add({left}, {right})"
            if op == TokenType.MINUS:
                return f"opal_sub({left}, {right})"
            if op == TokenType.STAR:
                return f"opal_mul({left}, {right})"
            if op in (TokenType.SLASH, TokenType.DIVIDE):
                return f"opal_div({left}, {right})"
            if op == TokenType.MODULO:
                return f"opal_mod({left}, {right})"
            if op == TokenType.POWER:
                return f"make_float(pow((double)({left}).int_val, (double)({right}).int_val))"
            if op == TokenType.EQ:
                return f"opal_eq({left}, {right})"
            if op == TokenType.NEQ:
                return f"make_bool(!opal_truthy(opal_eq({left}, {right})))"
            if op == TokenType.LT:
                return f"opal_lt({left}, {right})"
            if op == TokenType.GT:
                return f"opal_lt({right}, {left})"
            if op == TokenType.LTE:
                return f"make_bool(!opal_truthy(opal_lt({right}, {left})))"
            if op == TokenType.GTE:
                return f"make_bool(!opal_truthy(opal_lt({left}, {right})))"
            if op == TokenType.AND:
                return f"make_bool(opal_truthy({left}) && opal_truthy({right}))"
            if op == TokenType.OR:
                return f"make_bool(opal_truthy({left}) || opal_truthy({right}))"
            return f"/* unknown op {op} */ make_null()"

        if isinstance(expr, UnaryOp):
            operand = self._transpile_expression(expr.operand)
            if expr.op.type == TokenType.MINUS:
                return f"opal_sub(make_int(0), {operand})"
            if expr.op.type == TokenType.NOT:
                return f"make_bool(!opal_truthy({operand}))"
            return f"/* unknown unary */ {operand}"

        if isinstance(expr, Assignment):
            value = self._transpile_expression(expr.value)
            if isinstance(expr.target, Identifier):
                return f"{expr.target.name} = {value}"
            return f"/* assignment */ {value}"

        if isinstance(expr, CompoundAssign):
            value = self._transpile_expression(expr.value)
            if isinstance(expr.target, Identifier):
                name = expr.target.name
                op = expr.op.type
                if op == TokenType.PLUS_ASSIGN:
                    return f"{name} = opal_add({name}, {value})"
                if op == TokenType.MINUS_ASSIGN:
                    return f"{name} = opal_sub({name}, {value})"
                if op == TokenType.STAR_ASSIGN:
                    return f"{name} = opal_mul({name}, {value})"
                if op == TokenType.SLASH_ASSIGN:
                    return f"{name} = opal_div({name}, {value})"
            return f"/* compound assign */ {value}"

        if isinstance(expr, Call):
            args = ', '.join(self._transpile_expression(a) for a in expr.args)
            if isinstance(expr.callee, Identifier):
                # Map echo to print
                if expr.callee.name == 'echo':
                    if len(expr.args) == 1:
                        return f"opal_println({self._transpile_expression(expr.args[0])})"
                    # Multiple args - use opal_print_value sequence
                    code = "("
                    for i, a in enumerate(expr.args):
                        if i > 0:
                            code += ", "
                        code += f"opal_print_value({self._transpile_expression(a)})"
                    return code + ", printf(\"\\n\"), make_null())"
                return f"{expr.callee.name}({args})"
            return f"/* call */ make_null()"

        if isinstance(expr, TernaryExpr):
            cond = self._transpile_expression(expr.condition)
            then_v = self._transpile_expression(expr.then_expr)
            else_v = self._transpile_expression(expr.else_expr)
            return f"(opal_truthy({cond}) ? {then_v} : {else_v})"

        if isinstance(expr, MemberAccess):
            obj = self._transpile_expression(expr.obj)
            return f"/* member {expr.member} of {obj} */ make_null()"

        if isinstance(expr, IndexAccess):
            obj = self._transpile_expression(expr.obj)
            idx = self._transpile_expression(expr.index)
            return f"/* index {obj}[{idx}] */ make_null()"

        if isinstance(expr, ListLiteral):
            return "/* list literal */ make_null()"

        if isinstance(expr, Range):
            return "/* range */ make_null()"

        return "/* unknown expr */ make_null()"


def transpile_to_c(source, output_path=None):
    """تحويل كود أوبال إلى C / Transpile Opal source to C"""
    try:
        lexer = Lexer(source)
        tokens = lexer.tokenize()

        parser = Parser(tokens)
        program = parser.parse()

        transpiler = CTranspiler()
        c_code = transpiler.transpile(program)

        if output_path is None:
            output_path = "output.c"

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(c_code)

        return c_code, None

    except (LexError, ParseError) as e:
        return None, str(e)
    except Exception as e:
        return None, str(e)


def compile_file(filepath, output_path=None):
    """تحويل ملف أوبال إلى C / Compile Opal file to C"""
    if not os.path.exists(filepath):
        print(f"Error: File '{filepath}' not found")
        return False

    with open(filepath, 'r', encoding='utf-8') as f:
        source = f.read()

    if output_path is None:
        if filepath.endswith('.op'):
            output_path = filepath[:-3] + '.c'
        else:
            output_path = filepath + '.c'

    c_code, error = transpile_to_c(source, output_path)

    if error:
        print(f"Compile error: {error}")
        return False

    print(f"Generated: {output_path}")
    print(f"To compile: gcc {output_path} -o program -lm")
    return True
